application: mojishuffle
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: main.html
  upload: /

- url: .*
  script: htdocs

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
