application: mojishuffle
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: htdocs/main.html
  upload: /

- url: .*
  script: htdocs

libraries:
- name: webapp2
  version: "2.5.2"
